#!/usr/bin/env sh

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=display_added action="sleep 2 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

$HOME/.config/yabai/create_spaces.sh

yabai -m config window_border              on           \
                mouse_follows_focus        off          \
                focus_follows_mouse        off          \
                window_zoom_persist        off          \
                window_placement           second_child \
                window_topmost             off          \
                window_shadow              off        \
                window_opacity             on           \
                window_opacity_duration    0.15         \
                active_window_opacity      1.0          \
                normal_window_opacity      0.95         \
                window_animation_duration  0.22         \
                insert_feedback_color      0xff9dd274   \
                auto_balance               on          \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                top_padding                16           \
                bottom_padding             16           \
                left_padding               16           \
                right_padding              16           \
                window_gap                 16

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(Keymapp|Signal|LuLu|Vimac|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

yabai -m config layout bsp

borders active_color=0xffc4a7e7 inactive_color=0xff393552 width=8.0 

echo "yabai configuration loaded.."

